apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: deploy
spec:
        replicas: 3
        template:
                metadata:
                       labels:
                               app: app1
                spec:
                        containers:
                                - name: reactapplication
                                  image: reactimage
                                  ports:
                                          - containerPort: 3000
