apiVersion: v1
kind: Service
metadata:
        name: svc1
spec:
        ports:
                - port: 3000
                  targetPort: 32000
                  protocol: TCP
        selector:
                app: app1
        type: LoadBalancer
